#!/bin/bash

rm -f results.txt

for numThr in 1 2 4
	do
	#compile and execute fix 1
	for pad in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
	do
		/usr/local/common/gcc-7.3.0/bin/g++ -DFIXTYPE=1 -DNUMPAD=$pad -DNUMTHREADS=$numThr falseSharing.cpp -o p3fix1 -lm -fopenmp
		#execute
		./p3fix1
	done

	#compile and execute fix 2 (NUMPAD == 0, no padding for this fix type)
	/usr/local/common/gcc-7.3.0/bin/g++ -DFIXTYPE=2 -DNUMPAD=0 -DNUMTHREADS=$numThr falseSharing.cpp -o p3fix2 -lm -fopenmp
	#execute 
	./p3fix2
done
